project:
  type: website

website:
  title: "A. Solomon Kurz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog
      - href: Kurz_CV.pdf
        text: CV        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full



